<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <Platforms>AnyCPU</Platforms>
    <AssemblyName>ReceiptXcel 收據產生工具</AssemblyName>
    <Product>ReceiptXcel</Product>
    <Title>ReceiptXcel｜自行收納款項收據產生工具</Title>
    <Version>0.1.2</Version>
    <AssemblyVersion>0.1.2.0</AssemblyVersion>
    <FileVersion>0.1.2.0</FileVersion>
    <InformationalVersion>0.1.2</InformationalVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.104.2" />
    <PackageReference Include="DocumentFormat.OpenXml" Version="3.1.1" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Assets\Templates\receipt-template.docx" />
    <EmbeddedResource Include="Assets\Templates\receipt-template.docx"
                      LogicalName="ReceiptXcel.Templates.Receipt.docx" />
  </ItemGroup>

</Project>
